//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by w32_audio.rc
//
#define IDD_W32AUDIODLL_DIALOG_AUDIO_INPUT_SELECT 103
#define IDD_W32AUDIODLL_DIALOG_AUDIO_OUTPUT_SELECT 104
#define IDC_W32AUDIODLL_COMBO_MIXER     1000
#define IDC_W32AUDIODLL_COMBO_MXLINE    1001
#define IDC_W32AUDIODLL_COMBO_WAVEIN    1002
#define IDC_W32AUDIODLL_COMBO_WAVEOUT   1003
#define IDC_W32AUDIODLL_COMBO_SAMPLING  1004
#define IDC_W32AUDIODLL_CHECK_SHOW_ALL  1005
#define IDC_W32AUDIODLL_PROGRESS_DUTY_CYCLE 1006
#define IDC_W32AUDIODLL_COMBO_OUT_SAMPLING 1007
#define IDC_W32AUDIODLL_CHECK_OUT_SHOW_ALL 1008
#define IDC_W32AUDIODLL_STATIC_VOLUME_PCT 1009
#define IDC_W32AUDIODLL_WRITE_FILE      2000
#define IDC_COMBO_OUT_MODE_PUT          2001
#define IDC_BUTTON1                     2002
#define IDC_BUTTON_OTST                 2002
#define IDR_W32AUDIODLL_VERSION         58112

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        2001
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         2003
#define _APS_NEXT_SYMED_VALUE           2000
#endif
#endif
